### ISSUE TITLE
Unable login after changing my password

### ISSUE THREAD

**Issue by Sigamani301992** [ldaptive/aws-s3-sftp-azure-IdentityProvider#14]
Hi @ldaptive ,

Hope you are doing well ! 
Me and my users are getting the below error when we login to SFTP. This happens only when we reset the password. 
Could you please help on the below issue ? 

INFO Error: WS-Trust RST request returned http error: 500 and server response: <s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"> s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/soap/fault s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"> u:Id="_0"><u:Created>2021-10-19T16:26:34.790Z</u:Created><u:Expires>2021-10-19T16:31:34.790Z</u:Expires></u:Timestamp></o:Security></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value xmlns:a="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">a:FailedAuthentication xml:lang="en-GB">ID3242: The security token could not be authenticated or authorized.</s:Text></s:Reason></s:Fault></s:Body></s:Envelope>
at Logger.createError (/var/task/node_modules/adal-node/lib/log.js:216:13)
at Request._callback (/var/task/node_modules/adal-node/lib/util.js:130:25)
at Request.self.callback (/var/task/node_modules/request/request.js:185:22)
at Request.emit (events.js:314:20)
at Request.<anonymous> (/var/task/node_modules/request.

Thanks in advance, 
Sigamani S

**Comment by ldaptive** [comment]
Hello,

authentication happens on the MS side and is out of scope for this. Also MS has announced that they are killing support for Azure Graph API June of next year and moving forward only graph API will be supported. 

We have created a new version of this IDP that deals with only the graph API. I would suggest having a look at that code set as it could address your issues:

https://www.intelligentdiscovery.io/blogs/aws-sftp-custom-identity-provider-v2
