### ISSUE TITLE
Access denied from FTP client

### ISSUE THREAD

**Issue by MartinovicN** [ldaptive/aws-s3-sftp-azure-IdentityProvider#5]
Hello, first would like to thank you for sharing your implementation, in the start I had problems with CloudFormation Template and after with Lambda function on AWS, after resolving that all, by trying to connect to my SFTP server with my WinSCP client I'm getting Access denied, also by trying to log with other Azure AD users getting the same.

Will be glad if you have a hint on how to resolve that .

Thanks a lot

**Comment by ldaptive** [comment]
Let's take it one step at a time, can you validate that once you deploy the cloud formation template you can authenticate with the test user?

After you put the function from git hub, what error are you getting? Perhaps send me the output from cloudwatch logs.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MartinovicN** [comment]
Thanks for the fast response.

Actually i'm not getting any error anymore, getting always code 200 by testing on Lambda and API , but after I try to access the SFTP server with FTP client with my Azure user, it's showing in cloudwatch access denied not really big error, so it's not allowing me to access the service . 

Can it be that something is not right on my Azure part ? Because of my AAD License I can't add Groups to the app, so just added users, can that maybe the problem ?

**Comment by ldaptive** [comment]
it could be. Replace index.js with this file as i have comment out the membership validation and added in comments to better troubleshoot it. Paste that and see what you get via cloudwatch.

```javascript
const azure = require('./controllers/azure');
const policy = require('./bin/scopeDownPolicy').policy;

exports.handler = async (event) => {
    /** Getting our function environment Variables - these were set via the cloudformation stack */
    const bucket = process.env.S3BucketName;
    const s3Role = process.env.S3RoleArn;
    const domain = process.env.PrincipleDomain;
    const clientId = process.env.AzureClientId;
    const secret = process.env.AzureClientSecret;
    const grant = process.env.AzureGrantType;
    const groupId = process.env.AzureGroupMemberID;
    const userName = event.username.toLowerCase() + domain.toLowerCase();

    /** attempting to login user via API to get the Azure Tenant the user is a part of */

    console.log('this is the username that i am attempting to pass:', userName);
    var user = await azure.login(userName, event.password);
    if (!user.userId) {
        console.log('I did not find a user, erroring out')
        /** no user found returning from function and failing login via SFTP */
        return {};
    } else {
        /** We have a user - logging into tenant with app credentials to get our access token for Azure App */
        console.log('i was able to loginto azure and get a a tenant', user.tenantId);
        var appLogin = await azure.appLogin(user.tenantId, clientId, secret, grant);
        if(!appLogin){console.log('I was unable to login with the azure application')}
        if (!appLogin.access_token) {
            console.log('I did not get back an access token from azure')
            /** No Access token recieved - Returning with to fail login via SFTP */
            return {};
        } else {
            console.log('i am authenticated now and will return my response');
            /** Getting our member list from the supplied Azure AD group ID */
            var groupCheck = await azure.getGroupMembers(user.tenantId, groupId, appLogin.access_token);
            // var member = false;
            // /** validating our user is a member of the specified Azure AD Group */
            // groupCheck.forEach(x => {
            //     if (x.toLowerCase() === userName) {
            //         member = true;
            //     }
            // });

            /** We have a group memeber - returning access via SFTP */
            // if (member === true) {
                var response = {
                    Role: s3Role,
                    HomeBucket: bucket,
                    HomeDirectory: "/" + bucket + '/' + event.username.toLowerCase(),
                    Policy: JSON.stringify(policy)
                }
                return response;
            // } else {
                // return {}
            // }
        }

    }
}
```

**Comment by MartinovicN** [comment]
ok so added the js file getting the following:


ERRORS AUTH_FAILURE Method=password User=nmartinovic Message= SourceIP=

**Comment by MartinovicN** [comment]
so made a test with lambda and got this, remark all vital information have been replaced with -__------------


2020-09-30T15: 34: 25.589Z	1234566fe-3589-41b1-8a6d-b6ca77c13db8	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "StatusCodeError: 403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"----------------------------\\\",\\\"date\\\":\\\"2020-09-30T15:34:25\\\"}}\"",
    "reason": {
        "errorType": "StatusCodeError",
        "errorMessage": "403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"----------------------------\\\",\\\"date\\\":\\\"2020-09-30T15:34:25\\\"}}\"",
        "name": "StatusCodeError",
        "statusCode": 403,
        "message": "403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"----------------------------\\\",\\\"date\\\":\\\"2020-09-30T15:34:25\\\"}}\"",
        "error": "{\"odata.error\":{\"code\":\"Authorization_RequestDenied\",\"message\":{\"lang\":\"en\",\"value\":\"Insufficient privileges to complete the operation.\"},\"requestId\":\"----------------------------\",\"date\":\"2020-09-30T15:34:25\"}}",
        "options": {
            "uri": "https://graph.windows.net/6b-----------------------?$expand=members&api-version=1.6",
            "method": "GET",
            "headers": {
                "Accept": "application/json",
                "Authorization": "Bearer eyJ0eX-----"
            },
            "simple": true,
            "resolveWithFullResponse": false,
            "transform2xxOnly": false
        },
        "response": {
            "statusCode": 403,
            "body": "{\"odata.error\":{\"code\":\"Authorization_RequestDenied\",\"message\":{\"lang\":\"en\",\"value\":\"Insufficient privileges to complete the operation.\"},\"requestId\":\"----------------------------\",\"date\":\"2020-09-30T15:34:25\"}}",
            "headers": {
                "cache-control": "no-cache",
                "pragma": "no-cache",
                "content-type": "application/json; odata=minimalmetadata; streaming=true; charset=utf-8",
                "expires": "-1",
                "ocp-aad-diagnostics-server-name": "------------------------------------",
                "request-id": "----------------------------",
                "client-request-id": "-------------------------
                ",
                "x-ms-dirapi-data-contract-version": "1.6",
                "ocp-aad-session-key": "------------------------------------------------------------------------------------------------",
                "duration": "446111",
                "x-ms-resource-unit": "2",
                "dataserviceversion": "3.0;",
                "x-aspnet-version": "4.0.30319",
                "x-powered-by": "ASP.NET",
                "strict-transport-security": "max-age=31536000; includeSubDomains",
                "access-control-allow-origin": "*",
                "date": "Wed, 30 Sep 2020 15:34:25 GMT",
                "connection": "close",
                "content-length": "219"
            },
            "request": {
                "uri": {
                    "protocol": "https:",
                    "slashes": true,
                    "auth": null,
                    "host": "graph.windows.net",
                    "port": 443,
                    "hostname": "graph.windows.net",
                    "hash": null,
                    "search": "?$expand=members&api-version=1.6",
                    "query": "$expand=members&api-version=1.6",
                    "pathname": "/---------------------------------------",
                    "path": "/---------------------------------------?$expand=members&api-version=1.6",
                    "href": "https://graph.windows.net/---------------------------------------?$expand=members&api-version=1.6"
                },
                "method": "get",
                "headers": {
                    "Accept": "application/json",
                    "Authorization": "----------------------------------------------------------------",
                    "content-length": 0
                }
            }
        },
        "stack": [
            "StatusCodeError: 403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"----------------------------\\\",\\\"date\\\":\\\"2020-09-30T15:34:25\\\"}}\"",
            "    at new StatusCodeError (/var/task/node_modules/request-promise-core/lib/errors.js:32:15)",
            "    at Request.plumbing.callback (/var/task/node_modules/request-promise-core/lib/plumbing.js:104:33)",
            "    at Request.RP$callback [as _callback] (/var/task/node_modules/request-promise-core/lib/plumbing.js:46:31)",
            "    at Request.self.callback (/var/task/node_modules/request/request.js:185:22)",
            "    at Request.emit (events.js:315:20)",
            "    at Request.<anonymous> (/var/task/node_modules/request/request.js:1161:10)",
            "    at Request.emit (events.js:315:20)",
            "    at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1083:12)",
            "    at Object.onceWrapper (events.js:421:28)",
            "    at IncomingMessage.emit (events.js:327:22)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: StatusCodeError: 403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"----------------------------\\\",\\\"date\\\":\\\"2020-09-30T15:34:25\\\"}}\"",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:315:20)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}

**Comment by ldaptive** [comment]
2 things:
1. it doesn't look like index.js was replaced and uploaded to the lambda function as I am not seeing this being executed:
```javascript
console.log('this is the username that i am attempting to pass:', userName);
```
2. you having this:
```javascript
ERRORS AUTH_FAILURE Method=password User=nmartinovic Message= SourceIP=
```
which suggests you have not setup the environment variables as they should be: (see point #3 under "Setting up the API Gateway" as that would create a domain name as an environment variable in the lambda function "PrincipleDomain" where you should have your domain. Example my Office or Azure domain is listed as '@ldaptive.com' however you also have a second domain "<yourdomain>.onmicrosoft.com". under your failure you should see: 

```javascript
ERRORS AUTH_FAILURE Method=password User=nmartinovic@yourdomain.com Message= SourceIP=
```
or
```javascript
ERRORS AUTH_FAILURE Method=password User=nmartinovic@yourdomain.onmicrosoft.com Message= SourceIP=
```

**Comment by MartinovicN** [comment]
the 1 is done an the second is done also,here are the whole Log files : one by one  : 
1:
START RequestId: 123456-123-4453d-ba30-123ss456 Version: $LATEST
2:
123456-123-4453d-ba30-123ss456	INFO	this is the username that i am attempting to pass: nmartinovic@mydomain.onmicrosoft.com
3:
INFO	i was able to loginto azure and get a a tenant 123456-123-4453d-ba30-123ss4563 
4:
23456-123-4453d-ba30-123ss4563 INFO	i am authenticated now and will return my response
5:
ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "StatusCodeError: 403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"-------------------------------\\\",\\\"date\\\":\\\"2020-09-30T16:59:55\\\"}}\"",
    "reason": {
        "errorType": "StatusCodeError",
        "errorMessage": "403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"-------------------------------\\\",\\\"date\\\":\\\"2020-09-30T16:59:55\\\"}}\"",
        "name": "StatusCodeError",
        "statusCode": 403,
        "message": "403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"-------------------------------\\\",\\\"date\\\":\\\"2020-09-30T16:59:55\\\"}}\"",
        "error": "{\"odata.error\":{\"code\":\"Authorization_RequestDenied\",\"message\":{\"lang\":\"en\",\"value\":\"Insufficient privileges to complete the operation.\"},\"requestId\":\"-------------------------------\",\"date\":\"2020-09-30T16:59:55\"}}",
        "options": {
            "uri": "https://graph.windows.net/-------------------------------------groups/----------------------?$expand=members&api-version=1.6",
            "method": "GET",
            "headers": {
                "Accept": "application/json",
                "Authorization": "-----------------"
            },
            "simple": true,
            "resolveWithFullResponse": false,
            "transform2xxOnly": false
        },
        "response": {
            "statusCode": 403,
            "body": "{\"odata.error\":{\"code\":\"Authorization_RequestDenied\",\"message\":{\"lang\":\"en\",\"value\":\"Insufficient privileges to complete the operation.\"},\"requestId\":\"-------------------------------\",\"date\":\"2020-09-30T16:59:55\"}}",
            "headers": {
                "cache-control": "no-cache",
                "pragma": "no-cache",
                "content-length": "219",
                "content-type": "application/json; odata=minimalmetadata; streaming=true; charset=utf-8",
                "expires": "-1",
                "ocp-aad-diagnostics-server-name": "------------------------",
                "request-id": "-------------------------------",
                "client-request-id": "---------------------",
                "x-ms-dirapi-data-contract-version": "1.6",
                "ocp-aad-session-key": "-------------------------------------------------------------g",
                "duration": "258131",
                "x-ms-resource-unit": "2",
                "dataserviceversion": "3.0;",
                "x-aspnet-version": "4.0.30319",
                "x-powered-by": "ASP.NET",
                "strict-transport-security": "max-age=31536000; includeSubDomains",
                "access-control-allow-origin": "*",
                "date": "Wed, 30 Sep 2020 16:59:55 GMT",
                "connection": "close"
            },
            "request": {
                "uri": {
                    "protocol": "https:",
                    "slashes": true,
                    "auth": null,
                    "host": "graph.windows.net",
                    "port": 443,
                    "hostname": "graph.windows.net",
                    "hash": null,
                    "search": "?$expand=members&api-version=1.6",
                    "query": "$expand=members&api-version=1.6",
                    "pathname": "/-------------------------------------groups/----------------------",
                    "path": "/-------------------------------------groups/----------------------?$expand=members&api-version=1.6",
                    "href": "https://graph.windows.net/-------------------------------------groups/----------------------?$expand=members&api-version=1.6"
                },
                "method": "get",
                "headers": {
                    "Accept": "application/json",
                    "Authorization": "-----------------",
                    "content-length": 0
                }
            }
        },
        "stack": [
            "StatusCodeError: 403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"-------------------------------\\\",\\\"date\\\":\\\"2020-09-30T16:59:55\\\"}}\"",
            "    at new StatusCodeError (/var/task/node_modules/request-promise-core/lib/errors.js:32:15)",
            "    at Request.plumbing.callback (/var/task/node_modules/request-promise-core/lib/plumbing.js:104:33)",
            "    at Request.RP$callback [as _callback] (/var/task/node_modules/request-promise-core/lib/plumbing.js:46:31)",
            "    at Request.self.callback (/var/task/node_modules/request/request.js:185:22)",
            "    at Request.emit (events.js:315:20)",
            "    at Request.<anonymous> (/var/task/node_modules/request/request.js:1161:10)",
            "    at Request.emit (events.js:315:20)",
            "    at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1083:12)",
            "    at Object.onceWrapper (events.js:421:28)",
            "    at IncomingMessage.emit (events.js:327:22)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: StatusCodeError: 403 - \"{\\\"odata.error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":{\\\"lang\\\":\\\"en\\\",\\\"value\\\":\\\"Insufficient privileges to complete the operation.\\\"},\\\"requestId\\\":\\\"-------------------------------\\\",\\\"date\\\":\\\"2020-09-30T16:59:55\\\"}}\"",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:315:20)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"


6:
END RequestId: ---------------

7:
Unknown application error occurred

Thank you for your time.

**Comment by ldaptive** [comment]
it looks that your failure is going on with Azure directly. 

the first authentication that passes, is logging directly in the Azure main tenant (for all customers). 
you get back that your username and password was validated against your @mydomain.onmicrosoft.com and returns the actual tenant ID of the @mydomain.onmicrosoft.com is registered to.

next authentication comes from your azure application that you have created:
```javascript
//make sure you have set your application variables in lambda environment (on the lambda screen which should have been configured via step 3 - see last message)

    const clientId = process.env.AzureClientId;             //should be read from lambda console
    const secret = process.env.AzureClientSecret;         //should be read from lambda console
    const grant = process.env.AzureGrantType;             //should be read from lambda console


var appLogin = await azure.appLogin(user.tenantId, clientId, secret, grant);
```

one of 2 things is happening here:
1. not correct application credentials
2. not enough permission on the Azure application in order to allow you to login.
