### ISSUE TITLE
Azure Configuration

### ISSUE THREAD

**Issue by Sigamani301992** [ldaptive/aws-s3-sftp-azure-IdentityProvider#7]
Hi Dear, 

Im little bit struck at the configuration on Azure part. Im very new to Azure. Can you help me to achieve this ? 
Your help is much needed.

Thanks,

**Comment by Sigamani301992** [comment]
Some how i tried to configure Azure app. But receiving this error when tested the SFTP.

**Comment by Sigamani301992** [comment]
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "index.handler is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: index.handler is undefined or not exported",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}

**Comment by jhylton** [comment]
From your initial note, it looks like something is not configured correctly on function directly. 

"errorType": "Runtime.HandlerNotFound",
"errorMessage": "index.handler is undefined or not exported",

can you validate that your code inside the function has something like this:

```javascript
exports.handler = async(event) =>{
    //code here
};
```
if it is you can look to do full export of this by specifying:

```javascript
module.exports.handler = async(event)=>.....
```

your lambda function should be specifying the entry point of: index.handler.

**Comment by Sigamani301992** [comment]
Thank you .. the issue the index.js is not in the root directory . after moving it the issue gone and now the below issue. Please bear me im completely from infra background.  I have the controllers folder and inside it has azure.js file . but i dont know why this error is.


{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module './controllers/azure'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module './controllers/azure'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}

**Comment by ldaptive** [comment]
it sounds like you have not put your lambda function in the proper folder structure and such. 

Refer to AWS documentation on creating lambda functions with .zip files

https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html

**Comment by Sigamani301992** [comment]
Thank you so much ... Let me align the folder structure and test again .

**Comment by Sigamani301992** [comment]
Hello @ldaptive , 

Thank you so much for the link. after using NPM install im able to resolve those errors. 
But im getting the below errors,

**Error 1 :**

2021-03-22T16:09:49.206Z	bf87f041-82ac-4dba-b892-a12ae93629ae	INFO	Error: Server returned an unknown AccountType: undefined
    at Logger.createError (/var/task/node_modules/adal-node/lib/log.js:216:13)
    at /var/task/node_modules/adal-node/lib/token-request.js:437:46
    at UserRealm._parseDiscoveryResponse (/var/task/node_modules/adal-node/lib/user-realm.js:234:3)
    at /var/task/node_modules/adal-node/lib/user-realm.js:263:12
    at Request._callback (/var/task/node_modules/adal-node/lib/util.js:134:5)
    at Request.self.callback (/var/task/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/var/task/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1083:12)

**Error 2:**

2021-03-22T16:09:49.225Z	bf87f041-82ac-4dba-b892-a12ae93629ae	ERROR	Invoke Error 	{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'userId' of undefined",
    "stack": [
        "TypeError: Cannot read property 'userId' of undefined",
        "    at Runtime.exports.handler (/var/task/index.js:17:15)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}

Could you please help me please ?

Thanks , 
Sigamani S

**Comment by ldaptive** [comment]
It doesn't appear you are passing a valid username and password to azure to authenticate with as Error 2 states userId = undefined, specifically on line 17 of index.js

```javascript
    /** attempting to login user via API to get the Azure Tenant the user is a part of */
    var user = await azure.login(userName, event.password);
    //you are failing here! no user is being returned!
    if (!user.userId) {
        /** no user found returning from function and failing login via SFTP */
        return {};
    } else {
        .............
    }
```

you should look to console.log your userid and password (***for troubleshooting only***) to validate you are passing the correct login information and ensure your userId conforms to what sftp transfer accepts.

**Comment by Sigamani301992** [comment]
Thank you . @ldaptive  but im using the same username and password combination to login azure it is successful. 
now i simply give the user name without @domain.com im getting the below 2 errors. even it says token could not be authenticated. 

**error 1:**
2021-03-22T16:42:44.409Z	65415b47-376c-4372-b472-3876cc0d1ac7	INFO	Error: WS-Trust RST request returned http error: 500 and server response: <s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><s:Header><a:Action s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/soap/fault</a:Action><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><u:Timestamp u:Id="_0"><u:Created>2021-03-22T16:42:44.389Z</u:Created><u:Expires>2021-03-22T16:47:44.389Z</u:Expires></u:Timestamp></o:Security></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value xmlns:a="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">a:FailedAuthentication</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-GB">ID3242: The security token could not be authenticated or authorized.</s:Text></s:Reason></s:Fault></s:Body></s:Envelope>
    at Logger.createError (/var/task/node_modules/adal-node/lib/log.js:216:13)
    at Request._callback (/var/task/node_modules/adal-node/lib/util.js:130:25)
    at Request.self.callback (/var/task/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/var/task/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)

**error 2:**  same as the above one

2021-03-22T16:42:44.410Z	65415b47-376c-4372-b472-3876cc0d1ac7	ERROR	Invoke Error 	{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'userId' of undefined",
    "stack": [
        "TypeError: Cannot read property 'userId' of undefined",
        "    at Runtime.exports.handler (/var/task/index.js:17:15)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}

**Comment by Sigamani301992** [comment]
do we need to add any API permission for Azure Application which im using to Authenticate here ?

**Comment by ldaptive** [comment]
The first login is a direct login to Azure, which should look exactly how you would login to portal.azure.com. you can also try specifying the onmicrosoft.domain.com login to see if you get better results. The error to me seems more an issue with the username you are attempting to pass on the first go. Once you are authenticated, we get back your tenantId that will then authenticate you directly in your azureAD tenant against your application. You are not making it that far at present so it seems more an issue with your initial login to azure vs your application login with username validation.

**Comment by Sigamani301992** [comment]
thanks @ldaptive . Let me check with my Azure team and update the thread.

**Comment by Sigamani301992** [comment]
@ldaptive  i have tried with a different account and getting the below  resposne in cloudwatch,

021-03-22T23:44:41.750+05:30

Copy
2021-03-22T18:14:41.734Z	5eb69a13-9cfc-453f-a26e-17b4cdec6a6a	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "StatusCodeError: 401 - \"{\\\"error\\\":\\\"invalid_client\\\",\\\"error_description\\\":\\\"AADSTS7000215: Invalid client secret is provided.\\\\r\\\

**Comment by Sigamani301992** [comment]
Now im trying and not getting any cloud watch logs .. but in my powershell window i see the below as a response

Message               Response                             StatusCode Url
-------               --------                             ---------- ---
Internal server error {"message": "Internal server error"} 500

what could be the cause for this error ?

**Comment by ldaptive** [comment]
sounds like your first error passed, however you did not set up the client secret correctly in the cloud formation template and / or the lambda function as the blog suggests as azure client secret has been set incorrectly.

the 2nd error 500 sounds like you are passing a username with invalid characters for sftp. check the documentation but pretty sure it only supports [azAZ0-9_-]

**Comment by Sigamani301992** [comment]
@ldaptive Do we need to specify client secret value ? im specifying the client secret id in the cloud formation parameter.
Please correct me if im wrong.

Thanks,

**Comment by ldaptive** [comment]
you need to ensure all the settings that were required in the cloudFormation template were set. Validate you have these set in your function.

![image](https://user-images.githubusercontent.com/61184323/112047391-87adf780-8b4d-11eb-8970-a537d495b293.png)

**Comment by Sigamani301992** [comment]
Thank you for the quick response @ldaptive . Let me verify the client secret values with Azure Team. Will get back with an update.

Thank you so much for bearing me. ;)

**Comment by Sigamani301992** [comment]
Hello @ldaptive , It seems to be an issue the Azure app and now it is rectified and im able to login via winscp .
But when i try to access the root of my bucket it show access denied. Also the folders which im creating through WinScp is not reflecting in S3 bucket.
Can you help me on this please ?

Thanks,

**Comment by Sigamani301992** [comment]
@ldaptive , some how i solved the above mentioned issue by changing the scopedownpolicy js file. 
i have a query i have few hundred users who will need to access different buckets and different folders.
Forex : User1 logs in AWS SFTP with his AD credentials and after successful login he will need access to only a folder inside a bucket (not like MY_BUCKET/USER_NAME) a different folder inside a bucket.
            User 2 Logs in AWS SFTP and he would need to access all the buckets. 

is it possible to do that ?

Thanks,

**Comment by ldaptive** [comment]
Multiple folders in the same bucket have been tested, however not multiple buckets. It should be possible since all permissions are via the scoped policy and sets the required permissions.

**Comment by Sigamani301992** [comment]
Thank you @ldaptive, can you help me with scope down policy for multiple folders within a single bucket ? Also do we have any workaround for multiple buckets access yet ?

Thanks,

**Comment by ldaptive** [comment]
@Sigamani301992 ,

this is an example of a working solution that we came up with for a client that had this requirement. If you need a help with implementation you can reach out to info@ldaptive.com for a potential consultancy engagement for your needs. I'll offer support at best effort dealing with issues or problems with this current library and example, but not extending it.

**Comment by Sigamani301992** [comment]
Hello @ldaptive , Good day . hope you are doing well... 
Some how i managed to get required access to users. But i found that the azure.getGroupMembers method is getting only first twenty users in the group . 
Could you help me to get the complete list of users ? because we have more than 20 users in the group.. but only the firs twenty people are getting authenticated. 

Thanks in advance.
