### ISSUE TITLE
Group members restriction

### ISSUE THREAD

**Issue by Sigamani301992** [ldaptive/aws-s3-sftp-azure-IdentityProvider#9]
Hello @ldaptive , Good day . hope you are doing well...
Some how i managed to get required access to users. But i found that the azure.getGroupMembers method is getting only first 20 users in the group .
Could you help me to get the complete list of users ? because we have more than 20 users in the group.. but only the firs twenty people are getting authenticated.

Thanks in advance.

**Comment by jhylton** [comment]
https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http

perhaps change the URI in azure controller:

```javascript
/** getting our group membership from the graph api from the application token */
module.exports.getGroupMembers = (tenant, groupId, token) => new Promise(async (resolve, reject) => {
    var queryString = "api-version=1.6"
    var options = {
        //uri: "https://graph.windows.net/" + tenant + "/groups/" + groupId + "?$expand=members&" + queryString,
        uri: "https://graph.windows.net/" + tenant + "/groups/" + groupId + "/members?&" + queryString,
        method: "get",
        headers: {
            'Accept': 'application/json',
            'Authorization': 'Bearer ' + token
        },
    }
    var response = JSON.parse(await request(options));
    var members = [];
    response.members.forEach(x => {
        if (!members.includes(x.userPrincipalName.toLowerCase()));
        members.push(x.userPrincipalName.toLowerCase())
    });
    resolve(members);
});
```

**Comment by Sigamani301992** [comment]
thank you so much for the prompt response @ldaptive 
Yes @ldaptive i was about to change it in the controller. i will update and let you know the progress.

**Comment by Sigamani301992** [comment]
Hi @ldaptive , 

After changing response.members.forEach to response.value.forEach it got worked successfully. Now able to get all the members in a group. 

Thank you so much for helping me. :)
